services:
  django-web:
    build: .
    container_name: resume_reviewer
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      AI_PROVIDER: ${AI_PROVIDER}
      ENV: ${ENV}
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/files

volumes:
  static_volume:
  media_volume:
